### ISSUE TITLE
Can't excute python cuckoo.py

### ISSUE THREAD

**Issue by focaaby** [idanr1986/cuckoo-droid#16]
I have followed the [installation(guest on android avd)](http://cuckoo-droid.readthedocs.io/en/latest/installation/guest_android_avd/) and created a emulator already.

but run `python cuckoo.py` error:

```
2016-10-14 15:37:38,220 [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.apkinfo": No module named androguard.core.analysis.analysis
```

**Comment by idanr1986** [comment]
pip install androgurad

**Comment by jpcarneiro** [comment]
Hi, I am getting the same error, and already have androguard installed (I even reinstalled to make sure).
Any other ideas?
Chrs,
jc

**Comment by baomajesty1458** [comment]
me too!

**Comment by wickywaka** [comment]
The problem is with androgaurd version. CuckooDroid needs androguard 1.2 or something. I will recommed to start using the CuckooDroid from here: https://github.com/quoscient/cuckoo-droid

We had made a pull request but not sure when will it be accepted. I had also made some video tutorials which can be found on youtube and there you can see that I used an older version of androguard to fix this problem. Hope this helps.

**Comment by wickywaka** [comment]
Here is the link to the video tutorials: https://www.youtube.com/watch?v=mUoz71KfwLg&list=PLWHO6M8IznQBPzRlcrZ99LG0n4bktm0x8

**Comment by anhkhoa14592** [comment]
Hi all,

I found that when we use pip to install AndroidGuard, pip will git the lastest version of AndroidGuard (at the moment is 3.2.1). The lastest AndroidGuard requires matplotlib >= 3.0 library, but matplotlib only support python >3.5. 
*So that we must install the old AndroidGuard's version, here the solution*

1.  Download Android Guard 2.0 at [Android Guard 2.0](https://github.com/androguard/androguard/releases/tag/v2.0)
2. Extract it then run `sudo python setup install`
3. Finish.

**Comment by baomajesty1458** [comment]
Thank you so much!

Sent from Mail for Windows 10

**Comment by wickywaka** [comment]
Also check the cuckoodroid repositry on my profile. I fixed some bugs there
along with rooting problem.

anhkhoa14592 <notifications@github.com> schrieb am Fr., 28. Sep. 2018,
05:12:

**Comment by baomajesty1458** [comment]
Thank you so much

Vào 10:12 AM, T.6, 28 Th9, 2018 anhkhoa14592 <notifications@github.com> đã
viết:

**Comment by cuckoodroidproject** [comment]
Im getting the same error - 
CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.apkinfo": No module named androguard.core.analysis.analysis

I Downloaded the androguard version 1.2 and it still doesn't launch. I've tried to download  @waqarrashid33  repository but it fails in this command - git pull --allow-unrelated-histories --no-edit -s recursive -X theirs droid master but it says the repository doesn't exist.
Do you have any ideas how can I solve it?
Thanks!
